### ISSUE TITLE
interval at 5 secs?

### ISSUE THREAD

**Issue by siemvaessen** [markbrough/humportal-tests#1]
Hi,

It looks like the interval is set at 5 secs for this action. That is kind of not realistic, seeing a 1 minute interval is standard on many major monitoring tools. Hence the failed tests look like false positives us.

Could you set the interval to 60 secs?

Thanks

**Comment by markbrough** [comment]
By interval you mean how often the tests are run? They are run only every hour. See here:
https://github.com/markbrough/humportal-tests/actions

Perhaps you are referring to this line -- it runs five threads using [`pytest-xdist`](https://pypi.org/project/pytest-xdist/):
https://github.com/markbrough/humportal-tests/blob/master/.github/workflows/pythonapp.yml#L27

**Comment by markbrough** [comment]
Oh, you mean that it only waits 5 seconds before checking the respective elements?
https://github.com/markbrough/humportal-tests/blob/master/test_home.py#L10

**Comment by markbrough** [comment]
OK, I've updated that now :)

**Comment by siemvaessen** [comment]
yeap
